#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"
echo -e "=====\n>> Pre-push Hook: Checking branch name ..."

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCHES="^(master|main)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
    echo -e "\nThe target branch is `$BRANCH`, please versioning.\n"
    yarn version
fi

exit 0
